clean: Use standard cache directories in linux and darwin
codacy/codacy-coverage-reporter pull request #241
Opened 2020-08-18 12:05 UTC by lolgab

2020-08-19 08:28 UTC, andreaTP requested changes

2020-08-19 08:28 UTC, andreaTP commented on get.sh
> +        CODACY_REPORTER_TMP_FOLDER="~/.cache/codacy"
I would use `$HOME` instead of `~` for compatibility.

2020-08-19 08:29 UTC, andreaTP commented
A minor comment and is good for me, please check if we need to somehow update the documentation!

2020-08-19 10:19 UTC, lolgab commented on get.sh
> +        CODACY_REPORTER_TMP_FOLDER="~/.cache/codacy"
Done ✅

2020-08-19 10:26 UTC, rtfpessoa commented on src/main/scala/com/codacy/paths/PathsHelper.scala
> +    ???
Codacy found an issue: [Usage of ??? operator](https://app.codacy.com/gh/codacy/codacy-coverage-reporter/pullRequest?prid=6032356)

2020-08-19 10:26 UTC, rtfpessoa commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/gh/codacy/codacy-coverage-reporter/pullRequest?prid=6032356&bid=19769140)

2020-08-19 10:27 UTC, lolgab commented
@andreaTP Ready for another review round.

2020-08-19 10:33 UTC, andreaTP approved these changes

2020-09-22 16:12 UTC, pauloribeiro-codacy requested changes

2020-09-22 16:12 UTC, pauloribeiro-codacy commented on docs/alternative-ways-of-running-coverage-reporter.md
> +- `$HOME/Library/Caches/Codacy` on Mac OS X
Small language edits and make the list item indentation consistent:

```suggestion
The self-contained script is able to cache the binary. To avoid downloading the binary every time that the script runs, add one of the following directories to your CI cached folders:

-   `$HOME/.cache/codacy` on Linux
-   `$HOME/Library/Caches/Codacy` on Mac OS X
```

2020-09-22 16:32 UTC, pauloribeiro-codacy approved these changes

2020-09-24 07:55 UTC, franciscodua approved these changes

2020-09-25 16:10 UTC, merged