clean: Test validity of commit UUIDs and improve error messages [CY-2365, CY-2964]
codacy/codacy-coverage-reporter pull request #261
Opened 2020-09-29 17:04 UTC by afsmeira

2020-09-29 17:07 UTC, rtfpessoa commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/main/scala/com/codacy/rules/commituuid/CommitUUIDProvider.scala  2
- src/main/scala/com/codacy/rules/ConfigurationRules.scala  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/codacy/codacy-coverage-reporter/pullRequest?prid=6255549&bid=20370195)

2020-09-29 17:30 UTC, rtfpessoa requested changes

2020-09-29 17:30 UTC, rtfpessoa commented on src/main/scala/com/codacy/model/configuration/Configuration.scala
> +object CommitUUID {
Usually a nice pattern used in Scala is to have a trait defining the dto, and than the implementation (case class) has a private constructor that can only be created inside the companion object allowing for the error handling and guaranteeing that you cannot bad instances. What do you think about using it?

We have it for emails already in website/ragnaros

2020-09-29 17:30 UTC, rtfpessoa commented on src/main/scala/com/codacy/model/configuration/Configuration.scala
> +object CommitUUID {
It could also combine very well with the `Either[String, CommitUUID]` that ia already used in some places. This way we could probably avoid the `isValid` and just do composition.

2020-09-30 14:56 UTC, afsmeira commented on src/main/scala/com/codacy/model/configuration/Configuration.scala
> +object CommitUUID {
Yeah, that simplified some things.

2020-09-30 14:58 UTC, rtfpessoa commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/main/scala/com/codacy/rules/commituuid/CommitUUIDProvider.scala  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/codacy/codacy-coverage-reporter/pullRequest?prid=6255549&bid=20370195)

2020-09-30 15:07 UTC, jllopes approved these changes

2020-09-30 15:23 UTC, rtfpessoa commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/main/scala/com/codacy/rules/commituuid/CommitUUIDProvider.scala  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/codacy/codacy-coverage-reporter/pullRequest?prid=6255549&bid=20370195)

2020-10-01 09:51 UTC, rtfpessoa commented on src/main/scala/com/codacy/model/configuration/Configuration.scala
> +trait CommitUUID extends Any {
Add sealed to the trait to avoid having more instances

2020-10-01 09:54 UTC, rtfpessoa submitted a review, later dismissed

2020-10-01 09:54 UTC, rtfpessoa approved these changes

2020-10-01 09:57 UTC, rtfpessoa commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/main/scala/com/codacy/rules/commituuid/CommitUUIDProvider.scala  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/codacy/codacy-coverage-reporter/pullRequest?prid=6255549&bid=20370195)

2020-10-01 11:05 UTC, merged