docs: Add coverlet support
codacy/codacy-coverage-reporter pull request #334
Opened 2021-08-12 09:05 UTC by lucassklp

Signed-off-by: Lucas Simas <simas.lucas@hotmail.com>

2021-08-12 15:00 UTC, machadoit submitted a review, later dismissed
LGTM! ping @prcr

2021-08-12 15:24 UTC, prcr reviewed
Great contribution! :raised_hands: 

We can consider simplifying the information a bit, and I believe the supported LCOV format could be missing. Please see the comments. :+1:

2021-08-12 15:24 UTC, prcr commented on docs/index.md
> +    <td><a href="https://github.com/coverlet-coverage/coverlet#usage">Coverlet</a></td>
Here I'd link to the project repository instead of a specific section in the README, to help give more context to users:

```suggestion
    <td><a href="https://github.com/coverlet-coverage/coverlet">Coverlet</a></td>
```

2021-08-12 15:24 UTC, prcr commented on docs/index.md
> +        <a href="https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/MSBuildIntegration.md#coverage-output">See reference.</a>
For other tools, we're just listing the coverage report formats that the tool can output and that are compatible with Codacy.

Since Codacy doesn't have a "preferred" report format, we can simplify a bit by omitting information about which format is the default and the link to instructions on how to configure other outputs (saving us from keeping this information updated in the future). I'd also expect that the users will already be familiar with the tool and just need to confirm which report formats Codacy accepts.

Besides this, it seems that Coverlet can also output LCOV coverage reports, which is a format accepted by Codacy. So, should we also include it in the list? From what I could discover, it seems that the file name for LCOV reports is `coverage.info`, but I'm not 100% sure:

```suggestion
        <code>coverage.cobertura.xml</code> (Cobertura)<br />
        <code>coverage.opencover.xml</code> (OpenCover)<br />
        <code>coverage.info</code> (LCOV)
```

2021-08-17 10:17 UTC, lucassklp commented on docs/index.md
> +        <a href="https://github.com/coverlet-coverage/coverlet/blob/master/Documentation/MSBuildIntegration.md#coverage-output">See reference.</a>
I think the convention for filename is cobertura.<format>.xml, but I need to check it.

2021-08-17 10:18 UTC, machadoit commented
@lucassklp the PR is failing some tests, but if you rebase it with Master, that flackiness should be solved already

2021-08-17 14:15 UTC, machadoit requested changes
Please don't merge this for now, something is very off on the diff, why do many things appear? 🤔

2022-03-16 18:08 UTC, prcr commented
@lucassklp (and @machadoit) I don't know what triggered this pull request (perhaps there is a related Jira ticket?). Should we do a final push to get this released? :rocket:

2022-03-28 09:41 UTC, lucassklp commented
@prcr Vou ajustar essa branch, parece está com changes que não fazem parte da doc e desatualizada.

2022-04-29 09:54 UTC, prcr commented
I'm closing this pull request since it's now superseded by https://github.com/codacy/codacy-coverage-reporter/pull/378.

2022-04-29 09:54 UTC, closed without merging